export const Tag = {
  rss: {
    requiredTags: new Set(['channel']),
    validTags: new Set(['channel']),
    channel: {
      requiredTags: new Set(['title', 'item']),
      validTags: new Set([
        'title',
        'item',
        'link',
        'description',
        'language',
        'generator',
        'docs',
        'category',
        'image',
        'ttl',
        'pubDate',
        'lastBuildDate',
        'atom:link',
        'sy:updatePeriod',
        'sy:updateFrequency',
        'sy:updateBase',
      ]),
      item: {
        requiredTags: new Set(['title', 'guid', 'pubDate']),
        validTags: new Set([
          'title',
          'guid',
          'pubDate',
          'category',
          'description',
          'link',
          'author',
          'enclosure',
          'content:encoded',
          'media:content',
          'media:group',
          'atom:author',
          'atom:updated',
          'cf:hasAffiliateLinks',
          'cf:isSponsored',
          'cf:isPaid',
          'cf:liveCoverageState',
          'cf:thumbnail',
          'dc:creator',
          'dc:date',
          'dc:language',
          'dcterms:modified',
        ]),
      },
    },
  },
};
