name: '🚀 Publish'

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: https://npm.pkg.github.com
  NODE_VERSION: '18.18.2'

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        id: install_dependencies
        run: npm i

      - name: Test Code
        id: test_code
        run: npm run test

  release:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Github
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.REGISTRY }}
          scope: '@canvasflow'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pack
        run: npm pack --dry-run

      - name: publish
        run: npm publish --registry=${{ env.REGISTRY }}

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
