name: '🚀 Publish'

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: https://npm.pkg.github.com
  NODE_VERSION: '24.14.1'

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - run: npm i

      - name: 🧪 Test
        id: test_code
        run: npm run test

  release:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{ env.REGISTRY }}
          scope: '@canvasflow'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm ci

      - name: 🚜 Build
        run: npm run build

      - name: 📦 Pack
        run: npm pack --dry-run

      - name: 🚀 Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
